default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crashbreak_rails_example_development

test:
  <<: *default
  database: crashbreak_rails_example_test

production:
  <<: *default
  database: crashbreak_rails_example_production

crashbreak_test:
  <<: *default
  database: crashbreak-test